/**
 * Definições declarativas de camadas do GeoFogo Ceará.
 * Cada camada tem configuração completa: id, título, grupo, fonte, estilo, cache, etc.
 * Novas camadas podem ser adicionadas aqui sem alterar o componente do mapa.
 */

export const LAYER_GROUPS = {
  BASE: 'Mapas-base',
  LIMITS: 'Limites territoriais',
  FIRE: 'Incêndios',
  PROTECTED: 'Áreas protegidas',
  RESOURCES: 'Recursos operacionais',
  INFRA: 'Infraestrutura',
};

export const BASE_MAPS = {
  standard: {
    id: 'standard',
    title: 'Padrão',
    style: {
      version: 8,
      sources: {
        osm: {
          type: 'raster',
          tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],
          tileSize: 256,
          attribution: '© OpenStreetMap',
        },
      },
      layers: [{ id: 'osm', type: 'raster', source: 'osm' }],
    },
  },
  light: {
    id: 'light',
    title: 'Claro',
    style: {
      version: 8,
      sources: {
        carto: {
          type: 'raster',
          tiles: ['https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png'],
          tileSize: 256,
          attribution: '© CARTO © OpenStreetMap',
        },
      },
      layers: [{ id: 'carto', type: 'raster', source: 'carto' }],
    },
  },
  dark: {
    id: 'dark',
    title: 'Escuro',
    style: {
      version: 8,
      sources: {
        carto: {
          type: 'raster',
          tiles: ['https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png'],
          tileSize: 256,
          attribution: '© CARTO © OpenStreetMap',
        },
      },
      layers: [{ id: 'carto', type: 'raster', source: 'carto' }],
    },
  },
  satellite: {
    id: 'satellite',
    title: 'Satélite',
    style: {
      version: 8,
      sources: {
        esri: {
          type: 'raster',
          tiles: ['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],
          tileSize: 256,
          attribution: '© Esri',
        },
      },
      layers: [{ id: 'esri', type: 'raster', source: 'esri' }],
    },
  },
};

export const LAYER_DEFINITIONS = [
  {
    id: 'ceara-boundary',
    title: 'Limite do Ceará',
    group: LAYER_GROUPS.LIMITS,
    sourceType: 'geojson',
    geometryType: 'polygon',
    defaultVisible: true,
    minZoom: 4,
    maxZoom: 22,
    zIndex: 10,
    opacity: 1,
    cachePolicy: 'cache-first',
    interactive: true,
    paint: {
      'fill-color': '#f59e0b',
      'fill-opacity': 0.03,
      'line-color': '#f59e0b',
      'line-width': 2,
      'line-opacity': 0.9,
    },
  },
  {
    id: 'municipalities',
    title: 'Municípios',
    group: LAYER_GROUPS.LIMITS,
    sourceType: 'geojson',
    geometryType: 'polygon',
    defaultVisible: true,
    minZoom: 6,
    maxZoom: 22,
    zIndex: 20,
    opacity: 0.6,
    cachePolicy: 'cache-first',
    interactive: true,
    paint: {
      'fill-color': '#94a3b8',
      'fill-opacity': 0.04,
      'line-color': '#64748b',
      'line-width': 0.5,
      'line-opacity': 0.5,
    },
  },
  {
    id: 'conservation-units',
    title: 'Unidades de Conservação',
    group: LAYER_GROUPS.PROTECTED,
    sourceType: 'geojson',
    geometryType: 'polygon',
    defaultVisible: true,
    minZoom: 5,
    maxZoom: 22,
    zIndex: 30,
    opacity: 0.5,
    cachePolicy: 'cache-first',
    interactive: true,
    paint: {
      'fill-color': '#22c55e',
      'fill-opacity': 0.25,
      'line-color': '#16a34a',
      'line-width': 1,
      'line-opacity': 0.8,
    },
  },
  {
    id: 'fire-events',
    title: 'Eventos de fogo',
    group: LAYER_GROUPS.FIRE,
    sourceType: 'geojson',
    geometryType: 'polygon',
    defaultVisible: true,
    minZoom: 5,
    maxZoom: 22,
    zIndex: 50,
    opacity: 0.75,
    cachePolicy: 'network-first',
    interactive: true,
    refreshInterval: 15 * 60 * 1000,
    paint: {
      'fill-color': '#ef4444',
      'fill-opacity': 0.5,
      'line-color': '#dc2626',
      'line-width': 1,
      'line-opacity': 0.9,
    },
    markerColor: '#ef4444',
  },
  {
    id: 'fire-events-markers',
    title: 'Centroide dos eventos',
    group: LAYER_GROUPS.FIRE,
    sourceType: 'geojson',
    geometryType: 'point',
    defaultVisible: true,
    minZoom: 5,
    maxZoom: 22,
    zIndex: 51,
    opacity: 1,
    cachePolicy: 'network-first',
    interactive: true,
    derivedFrom: 'fire-events',
    paint: {
      'circle-radius': 6,
      'circle-color': '#f97316',
      'circle-stroke-color': '#ffffff',
      'circle-stroke-width': 1.5,
      'circle-stroke-opacity': 0.9,
    },
  },
  {
    id: 'fire-fronts',
    title: 'Frentes de fogo',
    group: LAYER_GROUPS.FIRE,
    sourceType: 'geojson',
    geometryType: 'point',
    defaultVisible: true,
    minZoom: 7,
    maxZoom: 22,
    zIndex: 52,
    opacity: 1,
    cachePolicy: 'network-first',
    interactive: true,
    paint: {
      'circle-radius': 4,
      'circle-color': '#fbbf24',
      'circle-stroke-color': '#dc2626',
      'circle-stroke-width': 1,
      'circle-stroke-opacity': 0.8,
    },
  },
  {
    id: 'alert-buffers',
    title: 'Buffer de alertas',
    group: LAYER_GROUPS.FIRE,
    sourceType: 'geojson',
    geometryType: 'polygon',
    defaultVisible: false,
    minZoom: 5,
    maxZoom: 22,
    zIndex: 45,
    opacity: 0.15,
    cachePolicy: 'local-first',
    interactive: false,
    paint: {
      'fill-color': '#f97316',
      'fill-opacity': 0.12,
      'line-color': '#f97316',
      'line-width': 0.5,
      'line-opacity': 0.4,
      'line-dasharray': [2, 2],
    },
  },
  {
    id: 'field-trail',
    title: 'Trilha do Modo Campo',
    group: LAYER_GROUPS.RESOURCES,
    sourceType: 'geojson',
    geometryType: 'linestring',
    defaultVisible: true,
    minZoom: 5,
    maxZoom: 22,
    zIndex: 60,
    opacity: 1,
    cachePolicy: 'local-first',
    interactive: false,
    paint: {
      'line-color': '#3b82f6',
      'line-width': 3,
      'line-opacity': 0.9,
    },
  },
  {
    id: 'field-points',
    title: 'Pontos do Modo Campo',
    group: LAYER_GROUPS.RESOURCES,
    sourceType: 'geojson',
    geometryType: 'point',
    defaultVisible: true,
    minZoom: 5,
    maxZoom: 22,
    zIndex: 61,
    opacity: 1,
    cachePolicy: 'local-first',
    interactive: true,
    paint: {
      'circle-radius': 5,
      'circle-color': '#3b82f6',
      'circle-stroke-color': '#ffffff',
      'circle-stroke-width': 2,
    },
  },
  {
    id: 'field-position',
    title: 'Posição atual (Modo Campo)',
    group: LAYER_GROUPS.RESOURCES,
    sourceType: 'geojson',
    geometryType: 'point',
    defaultVisible: true,
    minZoom: 1,
    maxZoom: 22,
    zIndex: 70,
    opacity: 1,
    cachePolicy: 'local-first',
    interactive: false,
    paint: {
      'circle-radius': 8,
      'circle-color': '#2563eb',
      'circle-stroke-color': '#ffffff',
      'circle-stroke-width': 3,
    },
  },
];